{"errorMessage": "'ACCOUNTS'", "errorType": "KeyError", "requestId": "", "stackTrace": ["  File \"/var/lang/lib/python3.13/importlib/__init__.py\", line 88, in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\n", "  File \"<frozen importlib._bootstrap>\", line 1387, in _gcd_import\n", "  File \"<frozen importlib._bootstrap>\", line 1360, in _find_and_load\n", "  File \"<frozen importlib._bootstrap>\", line 1331, in _find_and_load_unlocked\n", "  File \"<frozen importlib._bootstrap>\", line 935, in _load_unlocked\n", "  File \"<frozen importlib._bootstrap_external>\", line 1022, in exec_module\n", "  File \"<frozen importlib._bootstrap>\", line 488, in _call_with_frames_removed\n", "  File \"/var/task/index.py\", line 7, in <module>\n    ACCOUNTS = json.loads(os.environ['ACCOUNTS'])\n", "  File \"<frozen os>\", line 716, in __getitem__\n"]}